name = "HonoApp"
compatibility_date = "2023-01-01"
compatibility_flags = [ "nodejs_compat" ]

[placement]
mode = "smart"

[vars]
DABABASE_HOST = "localhost"
DABABASE_USERNAME = ""
DABABASE_PASSWORD = ""
DABABASE_NAME = ""
JWT_SECRET = "secret"
